"""Generate a HalfCheetah reward function from a natural-language goal.

Pipes the goal to local Gemma 4 e4b (~/Projekt/gemma/bin/gemma), saves the
returned code to generated_rewards/<slug>.py, and prints it. Does NOT
execute the generated function — inspect it first, then import it into a
copy of train_custom.py.

Usage: uv run python llm_reward.py "hop on one leg"
"""
import re
import subprocess
import sys
from pathlib import Path

GEMMA = "/Users/andersbj/Projekt/gemma/bin/gemma"

PROMPT_TEMPLATE = """Write a Python reward function for HalfCheetah-v5 (MuJoCo).

OBSERVATION (obs, 17-dim numpy array of float):
  obs[0]    torso z-position (height; ~0.5 standing)
  obs[1]    torso pitch angle (radians; 0 = level, positive = nose up)
  obs[2-4]  back leg joints: thigh, shin, foot angle
  obs[5-7]  front leg joints: thigh, shin, foot angle
  obs[8]    torso x-velocity   (same as info["x_velocity"])
  obs[9]    torso z-velocity
  obs[10]   torso angular velocity
  obs[11-16] joint angular velocities (back thigh/shin/foot, front thigh/shin/foot)

ACTION (action, 6-dim numpy array, range [-1, 1]):
  joint torques [bthigh, bshin, bfoot, fthigh, fshin, ffoot]

INFO dict (passed each step):
  info["reward_forward"]  native forward-velocity reward (positive when moving forward)
  info["reward_ctrl"]     native control cost (already a negative number)
  info["x_position"]      torso x coordinate
  info["x_velocity"]      torso x velocity

IMPORTANT: The goal is NOT necessarily to run forward. Read the goal carefully
and pick obs/action/info components that match it. Many goals do NOT involve
info["reward_forward"] at all.

EXAMPLES (study these — match the *style* for the new goal):

# Goal: "stand still and balanced"
def reward_fn(obs, action, info):
    upright = -abs(obs[1])              # penalize torso tilt
    still   = -abs(info["x_velocity"])  # penalize any motion
    return upright + still + info["reward_ctrl"]

# Goal: "jump as high as possible"
def reward_fn(obs, action, info):
    height   = obs[0]                   # torso height
    upward   = max(obs[9], 0.0)         # reward upward velocity, ignore downward
    no_drift = -abs(info["x_velocity"]) # discourage running away
    return 2.0 * height + upward + 0.5 * no_drift + info["reward_ctrl"]

GOAL: __GOAL__

Output ONLY a Python function with this exact signature — no markdown fences,
no prose, no explanation, no <channel> tags:

import numpy as np

def reward_fn(obs, action, info):
    ...
    return reward

Rules:
- Keep it under 20 lines.
- Include a small control-cost term (e.g. + info["reward_ctrl"]) unless the goal forbids it.
- Use only numpy — no other imports.
"""


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s[:50] or "reward"


def strip_fences(text: str) -> str:
    t = text.strip()
    # Gemma 4 leaks reasoning between <|channel>thought ... <channel|> markers.
    t = re.sub(r"<\|?channel[^>]*>.*?<\|?channel\|?>", "", t, flags=re.DOTALL)
    # Gemma special tokens that occasionally bleed into output.
    t = re.sub(r"<unused\d+>", "", t)
    t = re.sub(r"<(?:bos|eos|end_of_turn|start_of_turn)[^>]*>", "", t)
    # Markdown fences
    t = re.sub(r"^```(?:python|py)?\s*\n?", "", t)
    t = re.sub(r"\n?```\s*$", "", t)
    return t.strip()


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit('usage: python llm_reward.py "your goal description"')

    goal = sys.argv[1]
    prompt = PROMPT_TEMPLATE.replace("__GOAL__", goal)

    print(f"Asking Gemma 4 e4b for a reward function: {goal!r}")
    print("(first call loads the 4-bit model, ~10-30s on M-series)\n", flush=True)

    proc = subprocess.run(
        [GEMMA, prompt],
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        sys.exit(f"gemma exited {proc.returncode}\nstderr:\n{proc.stderr}")

    raw = proc.stdout
    if "ready." in raw:
        raw = raw.split("ready.", 1)[1]
    code = strip_fences(raw)

    Path("generated_rewards").mkdir(exist_ok=True)
    out_path = Path(f"generated_rewards/{slugify(goal)}.py")
    header = f'"""Goal: {goal}\nGenerated by Gemma 4 e4b — INSPECT BEFORE RUNNING."""\n\n'
    out_path.write_text(header + code + "\n")

    print("=" * 60)
    print(out_path.read_text())
    print("=" * 60)
    print(f"\nSaved to {out_path}")
    print("Inspect, then plug into train_custom.py to use it.")


if __name__ == "__main__":
    main()
