"""Goal: hop on one leg
Generated by Gemma 4 e4b — INSPECT BEFORE RUNNING."""

import numpy as np

def reward_fn(obs, action, info):
    # Goal: Hop on one leg. Primary goal is vertical movement (z-velocity).
    
    # 1. Reward vertical movement (z-velocity)
    vertical_velocity_reward = obs[9]
    
    # 2. Penalize horizontal drift (x-velocity)
    horizontal_penalty = -abs(info["x_velocity"]) * 0.5
    
    # 3. Penalize imbalance (pitch angle)
    tilt_penalty = -abs(obs[1]) * 0.5
    
    # 4. Include control cost
    control_cost = info["reward_ctrl"]
    
    # Combine rewards
    reward = vertical_velocity_reward + horizontal_penalty + tilt_penalty + control_cost
    
    return reward
