"""Goal: jump straight up repeatedly without moving sideways
Generated by Gemma 4 e4b — INSPECT BEFORE RUNNING."""

import numpy as np

def reward_fn(obs, action, info):
    # obs[0]: torso z-position (height)
    # obs[9]: torso z-velocity
    # info["x_velocity"]: torso x velocity
    
    # Primary reward: Upward velocity (driving the jump)
    upward_velocity_reward = obs[9]
    
    # Secondary reward: Height achieved (encourages reaching maximum height)
    height_reward = obs[0] * 0.1
    
    # Penalty: Horizontal movement (must be minimized)
    horizontal_penalty = -0.5 * abs(info["x_velocity"])
    
    # Total reward combines vertical motion, height, control cost, and penalty
    reward = upward_velocity_reward + height_reward + horizontal_penalty + info["reward_ctrl"]
    
    return reward
